name: BumpCosmology
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz
  - astropy
  - h5py
  - ipywidgets
  - jax
  - jupyterlab
  - lalsuite
  - matplotlib
  - numpy
  - numpyro
  - pytables
  - seaborn
  - tqdm
